services:
  - type: web
    name: ncu-loop-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: APP_URL
        value: https://smahiro080419-ship-it.github.io/NCU-Loop
      - key: ALLOWED_ORIGINS
        value: https://smahiro080419-ship-it.github.io
      - key: GOOGLE_SIGNIN_CLIENT_ID
        value: 20229136857-aaga250je2huolgu99tdhj5qaid0pjgv.apps.googleusercontent.com
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
